steps:
  - command: "echo Building \\$BUILDKITE_PIPELINE_NAME"
  - wait
  - trigger: trigger-dependents
    async: true
    build:
      env:
        PUBLISHED_DEPENDENCIES: $BUILDKITE_PIPELINE_NAME
        DEBUG_OUTPUT: true