name: Bump the version of the library on commit to master

on:
  push:
    branches:
      - master
    paths:
      - 'build-tools/**'

concurrency: 
  group: ${{ github.workflow }}

jobs:
  bump_version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main # Pretend master isn't a release branch
          pre_release_branches: master
          tag_prefix: bobapki-v
          append_to_pre_release_tag: rc
          dry_run: true

